
spring:
  datasource:
    password: LibraryApp
    url: jdbc:mysql://localhost:3306/librarydb
    username: LibraryApp
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    showsql: true