export enum DataState {
    INITIAL_STATE = "INITIAL_STATE",
    LOADING_STATE = "LOADING_STATE",
    LOADED_STATE = "LOADED_STATE",
    ERROR_STATE = "ERROR_STATE",
    FINISHED_STATE = "FINISHED_STATE"
}
