spring:
  datasource:
    url: jdbc:mysql://${server.ip_address}:3306/librarydb
    username: ${sql.username}
    password: ${sql.password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    showsql: true
openai:
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com/v1/chat/completions
    key: sk-0AJL2a0bYUdyxdMOf3-NOTAKEY-WQU15mMyzW1
server:
  ip_address: 'localhost'
  address: 0.0.0.0
sql:
  username: 'libraryapp'
  password: 'libraryApp2!'
